## step 1 loading data

In [2]:
import pandas as pd
df=pd.read_csv("hourly_weather_10_days.csv")
df.head() #gives first 5 rows as output from the csv file , if no value specified

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km
0,2023-03-01 00:00:00,16.6,74.4,5.7,1012.5,9.5
1,2023-03-01 01:00:00,16.2,78.5,5.0,1012.1,10.3
2,2023-03-01 02:00:00,15.3,73.3,4.7,NaN,11.1
3,2023-03-01 03:00:00,15.8,72.4,1.3,1005.0,8.9
4,2023-03-01 04:00:00,20.9,70.6,6.8,1016.3,9.8

In [3]:
print(df.to_string())

               timestamp  temperature_C  humidity_%  wind_speed_kmph  pressure_hPa  visibility_km
0    2023-03-01 00:00:00           16.6        74.4              5.7        1012.5            9.5
1    2023-03-01 01:00:00           16.2        78.5              5.0        1012.1           10.3
2    2023-03-01 02:00:00           15.3        73.3              4.7           NaN           11.1
3    2023-03-01 03:00:00           15.8        72.4              1.3        1005.0            8.9
4    2023-03-01 04:00:00           20.9        70.6              6.8        1016.3            9.8
5    2023-03-01 05:00:00           20.8        63.7              NaN        1017.9           10.8
6    2023-03-01 06:00:00           22.8        67.0             11.3        1002.3            9.0
7    2023-03-01 07:00:00           22.5        63.7             12.3        1018.6           10.9
8    2023-03-01 08:00:00           21.2        65.3             13.8        1017.3           10.7
9    2023-03-01 09:00:00           28.2        64.5             10.8        1009.6           11.0
10   2023-03-01 10:00:00            NaN        66.3             13.5        1013.7           11.5
11   2023-03-01 11:00:00           25.6        54.2             17.6        1012.5           10.2
12   2023-03-01 12:00:00           25.4        62.2             16.0        1012.0            9.3
13   2023-03-01 13:00:00           23.4        61.7             16.5        1022.9           10.6
14   2023-03-01 14:00:00           27.6        60.5             12.8        1007.8           10.7
15   2023-03-01 15:00:00           23.8        50.7             13.8        1009.8            9.9
16   2023-03-01 16:00:00           22.0         NaN             14.1        1014.8            9.1
17   2023-03-01 17:00:00           23.7        62.5              NaN        1018.2           10.8
18   2023-03-01 18:00:00           23.1        72.4              8.1        1011.4           10.9
19   2023-03-01 19:00:00           22.1        62.9              8.0        1012.6            NaN
20   2023-03-01 20:00:00           18.2        60.0              7.3        1005.7           11.5
21   2023-03-01 21:00:00           19.4         NaN              6.2        1009.4           10.5
22   2023-03-01 22:00:00           19.7        75.1              4.3        1012.5            9.6
23   2023-03-01 23:00:00           14.7        76.3              4.6        1011.6            9.5
24   2023-03-02 00:00:00           15.9        83.2              4.4        1007.1           11.4
25   2023-03-02 01:00:00           15.7        70.7              7.7        1011.1           10.5
26   2023-03-02 02:00:00           17.6        76.5              5.3        1022.4            9.9
27   2023-03-02 03:00:00           20.0        65.9              3.2        1017.8           11.8
28   2023-03-02 04:00:00           22.0        75.9              6.2         999.8           10.7
29   2023-03-02 05:00:00           21.2         NaN              9.7        1010.7            9.8
30   2023-03-02 06:00:00           22.7        78.2             11.3        1011.4            9.9
31   2023-03-02 07:00:00           21.5        73.8             11.0        1012.2            9.6
32   2023-03-02 08:00:00           23.6        58.5             12.8        1014.0            NaN
33   2023-03-02 09:00:00           28.7        63.4             13.4        1017.1           10.1
34   2023-03-02 10:00:00           20.5        52.2             16.3        1006.4           10.7
35   2023-03-02 11:00:00           25.1        58.4             14.1        1023.4            9.3
36   2023-03-02 12:00:00           22.1        51.8             14.4        1012.3            NaN
37   2023-03-02 13:00:00           24.5        51.9             12.5        1011.6           10.3
38   2023-03-02 14:00:00           22.6        59.6             12.7        1013.3            8.1
39   2023-03-02 15:00:00           21.9        64.3             14.0        1009.3           10.8
40   2023-03-02 16:00:00           23.9        68.7             12.8        1001.6            NaN
41   2023-03-02 17:00:00            NaN        67.6              NaN        1009.5           10.0
42   2023-03-02 18:00:00           24.2         NaN              7.6        1015.9            9.4
43   2023-03-02 19:00:00           22.0        64.9              9.7        1009.3           10.4
44   2023-03-02 20:00:00           19.9        67.1              8.0        1013.5            8.0
45   2023-03-02 21:00:00           18.8        66.1              6.9        1024.1           11.2
46   2023-03-02 22:00:00           16.5        76.1              5.9        1003.4           10.2
47   2023-03-02 23:00:00           18.0        78.1              4.3        1005.5            8.6
48   2023-03-03 00:00:00           13.6        78.7              6.7        1016.1           10.8
49   2023-03-03 01:00:00           15.7        75.3              5.5        1008.1           10.1
50   2023-03-03 02:00:00           18.5        76.1              6.7        1015.5           10.0
51   2023-03-03 03:00:00           15.9        68.9              6.6        1015.3           10.4
52   2023-03-03 04:00:00           25.7        64.3              8.4        1012.3           10.3
53   2023-03-03 05:00:00           20.9        68.1              8.4        1011.1           10.9
54   2023-03-03 06:00:00           20.8        50.0             10.9        1013.5           10.9
55   2023-03-03 07:00:00           20.7        65.0             12.8        1010.3            9.9
56   2023-03-03 08:00:00           22.3        70.3             10.3        1007.2            8.8
57   2023-03-03 09:00:00           25.7        62.3             16.7        1008.9           10.4
58   2023-03-03 10:00:00           24.8        62.7             15.8           NaN           10.6
59   2023-03-03 11:00:00           21.2        60.5             17.8        1008.0            8.9
60   2023-03-03 12:00:00           25.5         NaN             15.1        1012.1           10.5
61   2023-03-03 13:00:00           21.9        50.1             13.7        1007.6           10.7
62   2023-03-03 14:00:00           22.4        68.6             13.0        1012.1            9.2
63   2023-03-03 15:00:00           24.7        66.3             16.3        1007.8           10.9
64   2023-03-03 16:00:00           24.4        60.3             15.2        1019.9           10.2
65   2023-03-03 17:00:00            NaN        58.5             12.7        1015.0           10.1
66   2023-03-03 18:00:00           23.3         NaN              NaN        1027.0            9.1
67   2023-03-03 19:00:00           24.4        71.7              8.2        1014.1           11.5
68   2023-03-03 20:00:00           22.7        71.8              8.4        1020.2            NaN
69   2023-03-03 21:00:00           20.9        75.8              8.5        1009.3            NaN
70   2023-03-03 22:00:00           18.6        65.9              4.7        1010.3            8.8
71   2023-03-03 23:00:00           15.4        78.8              6.9        1021.9           10.0
72   2023-03-04 00:00:00           16.7        77.0              7.3        1017.7            8.9
73   2023-03-04 01:00:00           18.7        88.1              3.2        1012.8           10.6
74   2023-03-04 02:00:00           17.9        82.4              4.0        1011.4            9.7
75   2023-03-04 03:00:00           16.0        68.3              6.9        1023.1            9.1
76   2023-03-04 04:00:00           21.5        70.9              5.3        1023.8           10.1
77   2023-03-04 05:00:00           22.1        70.1              7.8           NaN            8.0
78   2023-03-04 06:00:00           27.1        65.1             12.7        1013.3           11.4
79   2023-03-04 07:00:00           23.7         NaN             12.7        1003.4           11.4
80   2023-03-04 08:00:00           21.9        60.3              NaN        1005.2            9.0
81   2023-03-04 09:00:00           24.2        54.0             11.3        1016.8            NaN
82   2023-03-04 10:00:00           26.8        57.6             13.0        1010.4           10.9
83   2023-03-04 11:00:00           24.4        60.0             17.0        1017.3           11.8
84   2023-03-04 12:00:00            NaN        54.8             15.9        1012.7            9.6
85   2023-03-04 13:00:00           25.7        56.5             12.8        1009.3            9.5
86   2023-03-04 14:00:00           24.0        59.1             14.8        1013.9            9.3
87   2023-03-04 15:00:00           19.5        62.4             14.7        1004.1           10.5
88   2023-03-04 16:00:00           23.0        57.1             12.0        1011.3           11.2
89   2023-03-04 17:00:00           23.7        59.7             12.2        1014.2            NaN
90   2023-03-04 18:00:00           19.8        72.7             12.0        1021.0            9.9
91   2023-03-04 19:00:00           21.1        78.0              4.7        1012.5            6.8
92   2023-03-04 20:00:00           18.7        68.7              6.5        1012.9            9.2
93   2023-03-04 21:00:00           20.8        70.1              6.4        1014.8            8.1
94   2023-03-04 22:00:00           19.7        76.0              7.3        1013.3            9.5
95   2023-03-04 23:00:00           15.9        76.1              8.2        1012.9           10.3
96   2023-03-05 00:00:00           19.7        70.6              NaN        1004.2           10.2
97   2023-03-05 01:00:00           12.4        76.6              5.0        1010.7           11.6
98   2023-03-05 02:00:00           18.7         NaN              4.8        1004.2           10.5
99   2023-03-05 03:00:00           18.9        76.1              6.3        1018.6            NaN
100  2023-03-05 04:00:00           21.2        76.3              5.5        1005.3           12.4
101  2023-03-05 05:00:00           21.0        66.1              6.8        1008.0            9.3
102  2023-03-05 06:00:00           19.6        74.5              7.8        1007.8            8.7
103  2023-03-05 07:00:00           20.5        61.1             11.9        1010.8           10.4
104  2023-03-05 08:00:00           24.7        67.2             12.9           NaN           12.1
105  2023-03-05 09:00:00            NaN        60.6             15.6        1008.8            9.0
106  2023-03-05 10:00:00           23.3        52.4             13.3        1017.1           10.1
107  2023-03-05 11:00:00           23.1        55.5             15.8        1013.2            9.8
108  2023-03-05 12:00:00           22.8        60.0             15.4        1011.6           12.6
109  2023-03-05 13:00:00           24.5        54.1             14.1        1019.7           10.0
110  2023-03-05 14:00:00           24.9        64.7             15.6           NaN            9.2
111  2023-03-05 15:00:00           24.7        68.6             12.3        1010.0           10.3
112  2023-03-05 16:00:00           24.1        55.8              NaN        1018.9            9.2
113  2023-03-05 17:00:00           22.5        59.4             10.5        1005.8           10.6
114  2023-03-05 18:00:00           24.2        59.9              9.2        1015.7            9.1
115  2023-03-05 19:00:00           23.3        62.9              8.7        1011.5            9.2
116  2023-03-05 20:00:00           22.2        75.8             10.0        1018.4            8.5
117  2023-03-05 21:00:00           23.9        69.1              5.6        1013.1           11.8
118  2023-03-05 22:00:00           16.8        78.9              7.3        1009.9            8.3
119  2023-03-05 23:00:00           18.4        82.3              6.0        1016.7            8.4
120  2023-03-06 00:00:00           17.8        82.1              6.0           NaN            8.4
121  2023-03-06 01:00:00           18.5        76.3              6.6        1008.9           10.7
122  2023-03-06 02:00:00           21.1        78.7              6.9        1012.2            9.6
123  2023-03-06 03:00:00           21.9        71.8              9.2        1015.1            9.2
124  2023-03-06 04:00:00           17.9        66.8              6.6        1003.6            8.8
125  2023-03-06 05:00:00           16.6        75.2              8.4           NaN           10.4
126  2023-03-06 06:00:00           23.3        64.9              8.5        1010.4           10.2
127  2023-03-06 07:00:00           24.8        65.0             10.4        1012.4            9.8
128  2023-03-06 08:00:00           22.5        70.7             10.8        1016.3           10.9
129  2023-03-06 09:00:00           26.0        53.3             13.3        1012.3           12.4
130  2023-03-06 10:00:00           25.4        56.0             13.5        1007.1           10.6
131  2023-03-06 11:00:00           24.3        57.0             14.7        1014.6            8.4
132  2023-03-06 12:00:00           26.2        67.1             15.0        1013.5           11.2
133  2023-03-06 13:00:00           20.8        53.1             16.3        1009.6            NaN
134  2023-03-06 14:00:00           21.3         NaN             13.9        1012.3            8.2
135  2023-03-06 15:00:00           22.7        59.3             12.3        1015.7           10.3
136  2023-03-06 16:00:00           24.7        56.5             12.6        1006.8            9.5
137  2023-03-06 17:00:00           23.5        67.7              NaN           NaN            8.2
138  2023-03-06 18:00:00           25.6        68.0              8.6           NaN            NaN
139  2023-03-06 19:00:00           23.2        78.6              NaN        1019.0            8.1
140  2023-03-06 20:00:00           23.9        69.5              6.4        1010.8           10.5
141  2023-03-06 21:00:00           15.5        73.1              NaN        1004.7           10.6
142  2023-03-06 22:00:00           19.8        73.7              4.3        1011.6            8.5
143  2023-03-06 23:00:00           17.3        77.3              3.7        1017.3           10.7
144  2023-03-07 00:00:00           15.8        78.5              NaN        1013.6           10.3
145  2023-03-07 01:00:00           17.6        71.1              6.6        1011.1           11.0
146  2023-03-07 02:00:00           17.9         NaN              3.7           NaN           10.8
147  2023-03-07 03:00:00            NaN        73.3              8.6        1008.6           10.5
148  2023-03-07 04:00:00           19.8        68.6              NaN        1004.2            9.8
149  2023-03-07 05:00:00           23.4        68.0              9.0        1007.4           10.0
150  2023-03-07 06:00:00           19.9        66.9              8.3        1015.0           10.0
151  2023-03-07 07:00:00           25.7        59.3             11.4        1015.2            9.8
152  2023-03-07 08:00:00           23.1        56.7             11.5         998.1            9.7
153  2023-03-07 09:00:00           25.9        65.3             13.6        1012.9            9.3
154  2023-03-07 10:00:00           24.4        57.3             15.3        1009.0           10.5
155  2023-03-07 11:00:00           22.5        53.9             16.2        1009.0            9.4
156  2023-03-07 12:00:00           24.8        64.4             14.6        1012.2           10.4
157  2023-03-07 13:00:00           24.5        62.3             14.9        1009.3            9.5
158  2023-03-07 14:00:00           24.2        62.5             15.0        1009.7            9.9
159  2023-03-07 15:00:00           22.9        56.9             13.6        1012.3            9.4
160  2023-03-07 16:00:00           20.0        60.5              NaN           NaN            9.0
161  2023-03-07 17:00:00           20.7        64.2              8.7        1002.6           10.3
162  2023-03-07 18:00:00           20.5        64.0              7.8        1016.8           11.0
163  2023-03-07 19:00:00           21.9        67.2              9.5        1009.0           11.3
164  2023-03-07 20:00:00           23.2        58.4              9.3           NaN            9.1
165  2023-03-07 21:00:00           15.4        75.0              5.6        1014.2            9.7
166  2023-03-07 22:00:00           15.3        72.0              7.3        1017.9           10.1
167  2023-03-07 23:00:00           17.6        80.8              3.9        1012.7           10.9
168  2023-03-08 00:00:00           13.5        76.1              6.2        1015.1            8.5
169  2023-03-08 01:00:00            NaN        83.3              5.2        1005.1            9.1
170  2023-03-08 02:00:00           17.4         NaN              5.5        1010.2            7.9
171  2023-03-08 03:00:00           14.8        78.5              6.4        1015.7            9.4
172  2023-03-08 04:00:00           21.2        70.5              7.1        1018.0            NaN
173  2023-03-08 05:00:00           18.5        67.7              8.4        1003.6           10.3
174  2023-03-08 06:00:00           21.6        68.0              8.1        1009.4            8.5
175  2023-03-08 07:00:00           23.4        68.0             13.5        1003.5           10.7
176  2023-03-08 08:00:00           26.0        56.9             11.3        1007.5            9.3
177  2023-03-08 09:00:00           22.3        62.2             13.8        1008.1            9.4
178  2023-03-08 10:00:00            NaN        62.8             16.9        1009.3            9.3
179  2023-03-08 11:00:00           24.9        63.0             13.9        1004.0            9.6
180  2023-03-08 12:00:00           23.7        61.8             15.3        1006.5           11.6
181  2023-03-08 13:00:00            NaN        63.8             15.2        1002.7           11.3
182  2023-03-08 14:00:00           24.6        49.9             13.6        1011.2            9.2
183  2023-03-08 15:00:00           23.6        60.6             14.2        1016.4           10.2
184  2023-03-08 16:00:00           25.5        61.3             10.6        1013.5            9.8
185  2023-03-08 17:00:00           24.4        72.1             11.3        1010.6           10.8
186  2023-03-08 18:00:00           22.5         NaN              7.5        1008.4            9.2
187  2023-03-08 19:00:00           21.5        71.8             11.1        1017.4            9.1
188  2023-03-08 20:00:00           19.0        67.7              6.5        1012.5            9.4
189  2023-03-08 21:00:00           17.3        80.9             10.3        1017.4            8.7
190  2023-03-08 22:00:00           15.2        66.2              3.8        1006.3            9.6
191  2023-03-08 23:00:00           17.9         NaN              5.7        1019.2           10.7
192  2023-03-09 00:00:00           14.3        83.8              6.3        1001.7            8.3
193  2023-03-09 01:00:00           17.3        86.6              4.4        1013.9           10.2
194  2023-03-09 02:00:00           15.6        73.2              5.4        1006.1           11.2
195  2023-03-09 03:00:00           21.5        64.1              5.8        1019.4           10.2
196  2023-03-09 04:00:00           17.8        61.9              8.9        1008.9            8.1
197  2023-03-09 05:00:00           21.2        72.3              7.9        1022.8            9.9
198  2023-03-09 06:00:00           20.6        62.0             11.2        1010.2            9.2
199  2023-03-09 07:00:00           21.3        68.0              8.8        1012.5           10.4
200  2023-03-09 08:00:00           22.8        61.0              NaN        1016.1            9.5
201  2023-03-09 09:00:00           21.2        56.9             15.5           NaN           11.4
202  2023-03-09 10:00:00           25.1        58.9             17.4        1013.3            9.6

In [4]:
df.tail()

,timestamp,temperature_C,humidity_%,wind_speed_kmph,pressure_hPa,visibility_km
235,2023-03-10 19:00:00,23.4,67.2,9.9,1016.9,8.2
236,2023-03-10 20:00:00,20.2,NaN,8.2,1013.7,10.3
237,2023-03-10 21:00:00,NaN,71.4,4.5,1001.7,10.7
238,2023-03-10 22:00:00,20.9,79.0,5.0,1017.7,8.9
239,2023-03-10 23:00:00,11.5,NaN,7.3,NaN,12.5

## step 2 data exploring

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   timestamp        240 non-null    object
 1   temperature_C    228 non-null    float64
 2   humidity_%       224 non-null    float64
 3   wind_speed_kmph  226 non-null    float64
 4   pressure_hPa     223 non-null    float64
 5   visibility_km    228 non-null    float64
dtypes: float64(5), object(1)
memory usage: 11.4+ KB

In [6]:
print(df.describe())

       temperature_C  humidity_%  wind_speed_kmph  pressure_hPa  visibility_km
count     228.000000  224.000000       226.000000    223.000000     228.000000
mean       21.315789   66.795982        10.105310   1011.884753       9.989474
std         3.421237    8.190300         3.940668      5.187080       1.022166
min        11.500000   47.800000         1.300000    998.100000       6.800000
25%        18.700000   61.075000         6.625000   1008.900000       9.275000
50%        21.900000   66.300000         9.800000   1012.100000      10.000000
75%        23.925000   72.725000        13.500000   1015.100000      10.700000
max        28.700000   88.100000        17.800000   1027.000000      12.600000

In [7]:
print(df.isna().sum())

timestamp           0
temperature_C      12
humidity_%         16
wind_speed_kmph    14
pressure_hPa       17
visibility_km      12
dtype: int64

## step 3 missing value handling

In [8]:
## TODO: Fill missing values
df.ffill(inplace=True)
print(df.to_string())

#justify approach 
"""I have used forward fill becuase we have hourly data of temperature of 10 days . 
The timestamp column did not have any missing values so using forward fill wasn't an issue there, 
also there is not much change in temperature data hourly """

               timestamp  temperature_C  humidity_%  wind_speed_kmph  pressure_hPa  visibility_km
0    2023-03-01 00:00:00           16.6        74.4              5.7        1012.5            9.5
1    2023-03-01 01:00:00           16.2        78.5              5.0        1012.1           10.3
2    2023-03-01 02:00:00           15.3        73.3              4.7        1012.1           11.1
3    2023-03-01 03:00:00           15.8        72.4              1.3        1005.0            8.9
4    2023-03-01 04:00:00           20.9        70.6              6.8        1016.3            9.8
5    2023-03-01 05:00:00           20.8        63.7              6.8        1017.9           10.8
6    2023-03-01 06:00:00           22.8        67.0             11.3        1002.3            9.0
7    2023-03-01 07:00:00           22.5        63.7             12.3        1018.6           10.9
8    2023-03-01 08:00:00           21.2        65.3             13.8        1017.3           10.7
9    2023-03-01 09:00:00           28.2        64.5             10.8        1009.6           11.0
10   2023-03-01 10:00:00           28.2        66.3             13.5        1013.7           11.5
11   2023-03-01 11:00:00           25.6        54.2             17.6        1012.5           10.2
12   2023-03-01 12:00:00           25.4        62.2             16.0        1012.0            9.3
13   2023-03-01 13:00:00           23.4        61.7             16.5        1022.9           10.6
14   2023-03-01 14:00:00           27.6        60.5             12.8        1007.8           10.7
15   2023-03-01 15:00:00           23.8        50.7             13.8        1009.8            9.9
16   2023-03-01 16:00:00           22.0        50.7             14.1        1014.8            9.1
17   2023-03-01 17:00:00           23.7        62.5             14.1        1018.2           10.8
18   2023-03-01 18:00:00           23.1        72.4              8.1        1011.4           10.9
19   2023-03-01 19:00:00           22.1        62.9              8.0        1012.6           10.9
20   2023-03-01 20:00:00           18.2        60.0              7.3        1005.7           11.5
21   2023-03-01 21:00:00           19.4        60.0              6.2        1009.4           10.5
22   2023-03-01 22:00:00           19.7        75.1              4.3        1012.5            9.6
23   2023-03-01 23:00:00           14.7        76.3              4.6        1011.6            9.5
24   2023-03-02 00:00:00           15.9        83.2              4.4        1007.1           11.4
25   2023-03-02 01:00:00           15.7        70.7              7.7        1011.1           10.5
26   2023-03-02 02:00:00           17.6        76.5              5.3        1022.4            9.9
27   2023-03-02 03:00:00           20.0        65.9              3.2        1017.8           11.8
28   2023-03-02 04:00:00           22.0        75.9              6.2         999.8           10.7
29   2023-03-02 05:00:00           21.2        75.9              9.7        1010.7            9.8
30   2023-03-02 06:00:00           22.7        78.2             11.3        1011.4            9.9
31   2023-03-02 07:00:00           21.5        73.8             11.0        1012.2            9.6
32   2023-03-02 08:00:00           23.6        58.5             12.8        1014.0            9.6
33   2023-03-02 09:00:00           28.7        63.4             13.4        1017.1           10.1
34   2023-03-02 10:00:00           20.5        52.2             16.3        1006.4           10.7
35   2023-03-02 11:00:00           25.1        58.4             14.1        1023.4            9.3
36   2023-03-02 12:00:00           22.1        51.8             14.4        1012.3            9.3
37   2023-03-02 13:00:00           24.5        51.9             12.5        1011.6           10.3
38   2023-03-02 14:00:00           22.6        59.6             12.7        1013.3            8.1
39   2023-03-02 15:00:00           21.9        64.3             14.0        1009.3           10.8
40   2023-03-02 16:00:00           23.9        68.7             12.8        1001.6           10.8
41   2023-03-02 17:00:00           23.9        67.6             12.8        1009.5           10.0
42   2023-03-02 18:00:00           24.2        67.6              7.6        1015.9            9.4
43   2023-03-02 19:00:00           22.0        64.9              9.7        1009.3           10.4
44   2023-03-02 20:00:00           19.9        67.1              8.0        1013.5            8.0
45   2023-03-02 21:00:00           18.8        66.1              6.9        1024.1           11.2
46   2023-03-02 22:00:00           16.5        76.1              5.9        1003.4           10.2
47   2023-03-02 23:00:00           18.0        78.1              4.3        1005.5            8.6
48   2023-03-03 00:00:00           13.6        78.7              6.7        1016.1           10.8
49   2023-03-03 01:00:00           15.7        75.3              5.5        1008.1           10.1
50   2023-03-03 02:00:00           18.5        76.1              6.7        1015.5           10.0
51   2023-03-03 03:00:00           15.9        68.9              6.6        1015.3           10.4
52   2023-03-03 04:00:00           25.7        64.3              8.4        1012.3           10.3
53   2023-03-03 05:00:00           20.9        68.1              8.4        1011.1           10.9
54   2023-03-03 06:00:00           20.8        50.0             10.9        1013.5           10.9
55   2023-03-03 07:00:00           20.7        65.0             12.8        1010.3            9.9
56   2023-03-03 08:00:00           22.3        70.3             10.3        1007.2            8.8
57   2023-03-03 09:00:00           25.7        62.3             16.7        1008.9           10.4
58   2023-03-03 10:00:00           24.8        62.7             15.8        1008.9           10.6
59   2023-03-03 11:00:00           21.2        60.5             17.8        1008.0            8.9
60   2023-03-03 12:00:00           25.5        60.5             15.1        1012.1           10.5
61   2023-03-03 13:00:00           21.9        50.1             13.7        1007.6           10.7
62   2023-03-03 14:00:00           22.4        68.6             13.0        1012.1            9.2
63   2023-03-03 15:00:00           24.7        66.3             16.3        1007.8           10.9
64   2023-03-03 16:00:00           24.4        60.3             15.2        1019.9           10.2
65   2023-03-03 17:00:00           24.4        58.5             12.7        1015.0           10.1
66   2023-03-03 18:00:00           23.3        58.5             12.7        1027.0            9.1
67   2023-03-03 19:00:00           24.4        71.7              8.2        1014.1           11.5
68   2023-03-03 20:00:00           22.7        71.8              8.4        1020.2           11.5
69   2023-03-03 21:00:00           20.9        75.8              8.5        1009.3           11.5
70   2023-03-03 22:00:00           18.6        65.9              4.7        1010.3            8.8
71   2023-03-03 23:00:00           15.4        78.8              6.9        1021.9           10.0
72   2023-03-04 00:00:00           16.7        77.0              7.3        1017.7            8.9
73   2023-03-04 01:00:00           18.7        88.1              3.2        1012.8           10.6
74   2023-03-04 02:00:00           17.9        82.4              4.0        1011.4            9.7
75   2023-03-04 03:00:00           16.0        68.3              6.9        1023.1            9.1
76   2023-03-04 04:00:00           21.5        70.9              5.3        1023.8           10.1
77   2023-03-04 05:00:00           22.1        70.1              7.8        1023.8            8.0
78   2023-03-04 06:00:00           27.1        65.1             12.7        1013.3           11.4
79   2023-03-04 07:00:00           23.7        65.1             12.7        1003.4           11.4
80   2023-03-04 08:00:00           21.9        60.3             12.7        1005.2            9.0
81   2023-03-04 09:00:00           24.2        54.0             11.3        1016.8            9.0
82   2023-03-04 10:00:00           26.8        57.6             13.0        1010.4           10.9
83   2023-03-04 11:00:00           24.4        60.0             17.0        1017.3           11.8
84   2023-03-04 12:00:00           24.4        54.8             15.9        1012.7            9.6
85   2023-03-04 13:00:00           25.7        56.5             12.8        1009.3            9.5
86   2023-03-04 14:00:00           24.0        59.1             14.8        1013.9            9.3
87   2023-03-04 15:00:00           19.5        62.4             14.7        1004.1           10.5
88   2023-03-04 16:00:00           23.0        57.1             12.0        1011.3           11.2
89   2023-03-04 17:00:00           23.7        59.7             12.2        1014.2           11.2
90   2023-03-04 18:00:00           19.8        72.7             12.0        1021.0            9.9
91   2023-03-04 19:00:00           21.1        78.0              4.7        1012.5            6.8
92   2023-03-04 20:00:00           18.7        68.7              6.5        1012.9            9.2
93   2023-03-04 21:00:00           20.8        70.1              6.4        1014.8            8.1
94   2023-03-04 22:00:00           19.7        76.0              7.3        1013.3            9.5
95   2023-03-04 23:00:00           15.9        76.1              8.2        1012.9           10.3
96   2023-03-05 00:00:00           19.7        70.6              8.2        1004.2           10.2
97   2023-03-05 01:00:00           12.4        76.6              5.0        1010.7           11.6
98   2023-03-05 02:00:00           18.7        76.6              4.8        1004.2           10.5
99   2023-03-05 03:00:00           18.9        76.1              6.3        1018.6           10.5
100  2023-03-05 04:00:00           21.2        76.3              5.5        1005.3           12.4
101  2023-03-05 05:00:00           21.0        66.1              6.8        1008.0            9.3
102  2023-03-05 06:00:00           19.6        74.5              7.8        1007.8            8.7
103  2023-03-05 07:00:00           20.5        61.1             11.9        1010.8           10.4
104  2023-03-05 08:00:00           24.7        67.2             12.9        1010.8           12.1
105  2023-03-05 09:00:00           24.7        60.6             15.6        1008.8            9.0
106  2023-03-05 10:00:00           23.3        52.4             13.3        1017.1           10.1
107  2023-03-05 11:00:00           23.1        55.5             15.8        1013.2            9.8
108  2023-03-05 12:00:00           22.8        60.0             15.4        1011.6           12.6
109  2023-03-05 13:00:00           24.5        54.1             14.1        1019.7           10.0
110  2023-03-05 14:00:00           24.9        64.7             15.6        1019.7            9.2
111  2023-03-05 15:00:00           24.7        68.6             12.3        1010.0           10.3
112  2023-03-05 16:00:00           24.1        55.8             12.3        1018.9            9.2
113  2023-03-05 17:00:00           22.5        59.4             10.5        1005.8           10.6
114  2023-03-05 18:00:00           24.2        59.9              9.2        1015.7            9.1
115  2023-03-05 19:00:00           23.3        62.9              8.7        1011.5            9.2
116  2023-03-05 20:00:00           22.2        75.8             10.0        1018.4            8.5
117  2023-03-05 21:00:00           23.9        69.1              5.6        1013.1           11.8
118  2023-03-05 22:00:00           16.8        78.9              7.3        1009.9            8.3
119  2023-03-05 23:00:00           18.4        82.3              6.0        1016.7            8.4
120  2023-03-06 00:00:00           17.8        82.1              6.0        1016.7            8.4
121  2023-03-06 01:00:00           18.5        76.3              6.6        1008.9           10.7
122  2023-03-06 02:00:00           21.1        78.7              6.9        1012.2            9.6
123  2023-03-06 03:00:00           21.9        71.8              9.2        1015.1            9.2
124  2023-03-06 04:00:00           17.9        66.8              6.6        1003.6            8.8
125  2023-03-06 05:00:00           16.6        75.2              8.4        1003.6           10.4
126  2023-03-06 06:00:00           23.3        64.9              8.5        1010.4           10.2
127  2023-03-06 07:00:00           24.8        65.0             10.4        1012.4            9.8
128  2023-03-06 08:00:00           22.5        70.7             10.8        1016.3           10.9
129  2023-03-06 09:00:00           26.0        53.3             13.3        1012.3           12.4
130  2023-03-06 10:00:00           25.4        56.0             13.5        1007.1           10.6
131  2023-03-06 11:00:00           24.3        57.0             14.7        1014.6            8.4
132  2023-03-06 12:00:00           26.2        67.1             15.0        1013.5           11.2
133  2023-03-06 13:00:00           20.8        53.1             16.3        1009.6           11.2
134  2023-03-06 14:00:00           21.3        53.1             13.9        1012.3            8.2
135  2023-03-06 15:00:00           22.7        59.3             12.3        1015.7           10.3
136  2023-03-06 16:00:00           24.7        56.5             12.6        1006.8            9.5
137  2023-03-06 17:00:00           23.5        67.7             12.6        1006.8            8.2
138  2023-03-06 18:00:00           25.6        68.0              8.6        1006.8            8.2
139  2023-03-06 19:00:00           23.2        78.6              8.6        1019.0            8.1
140  2023-03-06 20:00:00           23.9        69.5              6.4        1010.8           10.5
141  2023-03-06 21:00:00           15.5        73.1              6.4        1004.7           10.6
142  2023-03-06 22:00:00           19.8        73.7              4.3        1011.6            8.5
143  2023-03-06 23:00:00           17.3        77.3              3.7        1017.3           10.7
144  2023-03-07 00:00:00           15.8        78.5              3.7        1013.6           10.3
145  2023-03-07 01:00:00           17.6        71.1              6.6        1011.1           11.0
146  2023-03-07 02:00:00           17.9        71.1              3.7        1011.1           10.8
147  2023-03-07 03:00:00           17.9        73.3              8.6        1008.6           10.5
148  2023-03-07 04:00:00           19.8        68.6              8.6        1004.2            9.8
149  2023-03-07 05:00:00           23.4        68.0              9.0        1007.4           10.0
150  2023-03-07 06:00:00           19.9        66.9              8.3        1015.0           10.0
151  2023-03-07 07:00:00           25.7        59.3             11.4        1015.2            9.8
152  2023-03-07 08:00:00           23.1        56.7             11.5         998.1            9.7
153  2023-03-07 09:00:00           25.9        65.3             13.6        1012.9            9.3
154  2023-03-07 10:00:00           24.4        57.3             15.3        1009.0           10.5
155  2023-03-07 11:00:00           22.5        53.9             16.2        1009.0            9.4
156  2023-03-07 12:00:00           24.8        64.4             14.6        1012.2           10.4
157  2023-03-07 13:00:00           24.5        62.3             14.9        1009.3            9.5
158  2023-03-07 14:00:00           24.2        62.5             15.0        1009.7            9.9
159  2023-03-07 15:00:00           22.9        56.9             13.6        1012.3            9.4
160  2023-03-07 16:00:00           20.0        60.5             13.6        1012.3            9.0
161  2023-03-07 17:00:00           20.7        64.2              8.7        1002.6           10.3
162  2023-03-07 18:00:00           20.5        64.0              7.8        1016.8           11.0
163  2023-03-07 19:00:00           21.9        67.2              9.5        1009.0           11.3
164  2023-03-07 20:00:00           23.2        58.4              9.3        1009.0            9.1
165  2023-03-07 21:00:00           15.4        75.0              5.6        1014.2            9.7
166  2023-03-07 22:00:00           15.3        72.0              7.3        1017.9           10.1
167  2023-03-07 23:00:00           17.6        80.8              3.9        1012.7           10.9
168  2023-03-08 00:00:00           13.5        76.1              6.2        1015.1            8.5
169  2023-03-08 01:00:00           13.5        83.3              5.2        1005.1            9.1
170  2023-03-08 02:00:00           17.4        83.3              5.5        1010.2            7.9
171  2023-03-08 03:00:00           14.8        78.5              6.4        1015.7            9.4
172  2023-03-08 04:00:00           21.2        70.5              7.1        1018.0            9.4
173  2023-03-08 05:00:00           18.5        67.7              8.4        1003.6           10.3
174  2023-03-08 06:00:00           21.6        68.0              8.1        1009.4            8.5
175  2023-03-08 07:00:00           23.4        68.0             13.5        1003.5           10.7
176  2023-03-08 08:00:00           26.0        56.9             11.3        1007.5            9.3
177  2023-03-08 09:00:00           22.3        62.2             13.8        1008.1            9.4
178  2023-03-08 10:00:00           22.3        62.8             16.9        1009.3            9.3
179  2023-03-08 11:00:00           24.9        63.0             13.9        1004.0            9.6
180  2023-03-08 12:00:00           23.7        61.8             15.3        1006.5           11.6
181  2023-03-08 13:00:00           23.7        63.8             15.2        1002.7           11.3
182  2023-03-08 14:00:00           24.6        49.9             13.6        1011.2            9.2
183  2023-03-08 15:00:00           23.6        60.6             14.2        1016.4           10.2
184  2023-03-08 16:00:00           25.5        61.3             10.6        1013.5            9.8
185  2023-03-08 17:00:00           24.4        72.1             11.3        1010.6           10.8
186  2023-03-08 18:00:00           22.5        72.1              7.5        1008.4            9.2
187  2023-03-08 19:00:00           21.5        71.8             11.1        1017.4            9.1
188  2023-03-08 20:00:00           19.0        67.7              6.5        1012.5            9.4
189  2023-03-08 21:00:00           17.3        80.9             10.3        1017.4            8.7
190  2023-03-08 22:00:00           15.2        66.2              3.8        1006.3            9.6
191  2023-03-08 23:00:00           17.9        66.2              5.7        1019.2           10.7
192  2023-03-09 00:00:00           14.3        83.8              6.3        1001.7            8.3
193  2023-03-09 01:00:00           17.3        86.6              4.4        1013.9           10.2
194  2023-03-09 02:00:00           15.6        73.2              5.4        1006.1           11.2
195  2023-03-09 03:00:00           21.5        64.1              5.8        1019.4           10.2
196  2023-03-09 04:00:00           17.8        61.9              8.9        1008.9            8.1
197  2023-03-09 05:00:00           21.2        72.3              7.9        1022.8            9.9
198  2023-03-09 06:00:00           20.6        62.0             11.2        1010.2            9.2
199  2023-03-09 07:00:00           21.3        68.0              8.8        1012.5           10.4
200  2023-03-09 08:00:00           22.8        61.0              8.8        1016.1            9.5
201  2023-03-09 09:00:00           21.2        56.9             15.5        1016.1           11.4
202  2023-03-09 10:00:00           25.1        58.9             17.4        1013.3            9.6

"I have used forward fill becuase we have hourly data of temperature of 10 days . \nThe timestamp column did not have any missing values so using forward fill wasn't an issue there, \nalso there is not much change in temperature data hourly "

## step 4 data analysis

In [11]:
#Calculate daily average temperature
avg_temp= df["temperature_C"].mean()
print("average temperature:",avg_temp)

#Find max, min, mean for each metric
print("\n min values:\n" , df.min())
print("\n max values:\n", df.max())
print("\n mean values:\n", df.select_dtypes(include='number').mean())

average temperature: 21.389583333333334

 min values:
 timestamp          2023-03-01 00:00:00
temperature_C                     11.5
humidity_%                        47.8
wind_speed_kmph                    1.3
pressure_hPa                     998.1
visibility_km                      6.8
dtype: object

 max values:
 timestamp          2023-03-10 23:00:00
temperature_C                     28.7
humidity_%                        88.1
wind_speed_kmph                   17.8
pressure_hPa                    1027.0
visibility_km                     12.6
dtype: object

 mean values:
 temperature_C        21.389583
humidity_%           66.798750
wind_speed_kmph      10.107083
pressure_hPa       1011.915833
visibility_km        10.002917
dtype: float64

In [15]:
# Which hour of the day is the most humid on average?
df["timestamp"] = pd.to_datetime(df["timestamp"])   
df["hour"] = df["timestamp"].dt.hour                
hourly_avg_humidity = df.groupby("hour")["humidity_%"].mean()
print(hourly_avg_humidity)
most_humid_hour = hourly_avg_humidity.idxmax()
print("Most humid hour on average:", most_humid_hour, "\nhumidity%:", hourly_avg_humidity.max())

hour
0     78.17
1     78.42
2     75.89
3     71.94
4     69.31
5     69.34
6     65.77
7     65.05
8     63.49
9     59.65
10    58.71
11    58.91
12    59.53
13    58.33
14    60.54
15    61.05
16    58.71
17    64.03
18    66.70
19    69.19
20    67.46
21    71.43
22    73.75
23    77.80
Name: humidity_%, dtype: float64
Most humid hour on average: 1
humidity%: 78.41999999999999

## Numpy Matrix Exercises

In [16]:
# TODO: Extract temperature and wind_speed as NumPy arrays
import numpy as np

temp = df['temperature_C'].to_numpy()
print("temp:", temp)
wind = df['wind_speed_kmph'].to_numpy()
print("wind:", wind)

temp: [16.6 16.2 15.3 15.8 20.9 20.8 22.8 22.5 21.2 28.2 28.2 25.6 25.4 23.4
 27.6 23.8 22.  23.7 23.1 22.1 18.2 19.4 19.7 14.7 15.9 15.7 17.6 20.
 22.  21.2 22.7 21.5 23.6 28.7 20.5 25.1 22.1 24.5 22.6 21.9 23.9 23.9
 24.2 22.  19.9 18.8 16.5 18.  13.6 15.7 18.5 15.9 25.7 20.9 20.8 20.7
 22.3 25.7 24.8 21.2 25.5 21.9 22.4 24.7 24.4 24.4 23.3 24.4 22.7 20.9
 18.6 15.4 16.7 18.7 17.9 16.  21.5 22.1 27.1 23.7 21.9 24.2 26.8 24.4
 24.4 25.7 24.  19.5 23.  23.7 19.8 21.1 18.7 20.8 19.7 15.9 19.7 12.4
 18.7 18.9 21.2 21.  19.6 20.5 24.7 24.7 23.3 23.1 22.8 24.5 24.9 24.7
 24.1 22.5 24.2 23.3 22.2 23.9 16.8 18.4 17.8 18.5 21.1 21.9 17.9 16.6
 23.3 24.8 22.5 26.  25.4 24.3 26.2 20.8 21.3 22.7 24.7 23.5 25.6 23.2
 23.9 15.5 19.8 17.3 15.8 17.6 17.9 17.9 19.8 23.4 19.9 25.7 23.1 25.9
 24.4 22.5 24.8 24.5 24.2 22.9 20.  20.7 20.5 21.9 23.2 15.4 15.3 17.6
 13.5 13.5 17.4 14.8 21.2 18.5 21.6 23.4 26.  22.3 22.3 24.9 23.7 23.7
 24.6 23.6 25.5 24.4 22.5 21.5 19.  17.3 15.2 17.9 14.3 17.3 15.6 21.5
 17.8 21.2 20.6 21.3 22.8 21.2 25.1 25.7 27.1 25.  25.  23.7 21.5 24.3
 23.6 18.6 19.6 14.7 19.  16.2 17.7 16.3 16.8 17.3 20.  21.8 23.3 24.4
 24.1 28.5 25.8 25.3 25.3 23.7 24.  22.7 24.2 22.6 21.2 23.4 20.2 20.2
 20.9 11.5]
wind: [ 5.7  5.   4.7  1.3  6.8  6.8 11.3 12.3 13.8 10.8 13.5 17.6 16.  16.5
 12.8 13.8 14.1 14.1  8.1  8.   7.3  6.2  4.3  4.6  4.4  7.7  5.3  3.2
  6.2  9.7 11.3 11.  12.8 13.4 16.3 14.1 14.4 12.5 12.7 14.  12.8 12.8
  7.6  9.7  8.   6.9  5.9  4.3  6.7  5.5  6.7  6.6  8.4  8.4 10.9 12.8
 10.3 16.7 15.8 17.8 15.1 13.7 13.  16.3 15.2 12.7 12.7  8.2  8.4  8.5
  4.7  6.9  7.3  3.2  4.   6.9  5.3  7.8 12.7 12.7 12.7 11.3 13.  17.
 15.9 12.8 14.8 14.7 12.  12.2 12.   4.7  6.5  6.4  7.3  8.2  8.2  5.
  4.8  6.3  5.5  6.8  7.8 11.9 12.9 15.6 13.3 15.8 15.4 14.1 15.6 12.3
 12.3 10.5  9.2  8.7 10.   5.6  7.3  6.   6.   6.6  6.9  9.2  6.6  8.4
  8.5 10.4 10.8 13.3 13.5 14.7 15.  16.3 13.9 12.3 12.6 12.6  8.6  8.6
  6.4  6.4  4.3  3.7  3.7  6.6  3.7  8.6  8.6  9.   8.3 11.4 11.5 13.6
 15.3 16.2 14.6 14.9 15.  13.6 13.6  8.7  7.8  9.5  9.3  5.6  7.3  3.9
  6.2  5.2  5.5  6.4  7.1  8.4  8.1 13.5 11.3 13.8 16.9 13.9 15.3 15.2
 13.6 14.2 10.6 11.3  7.5 11.1  6.5 10.3  3.8  5.7  6.3  4.4  5.4  5.8
  8.9  7.9 11.2  8.8  8.8 15.5 17.4 13.5 14.8 17.4 12.2 13.4 15.4 11.
 10.9  6.5  7.8  6.8  4.4  6.3  6.4  5.9  4.5  7.2  9.7 10.2  9.6 11.6
 13.1 11.5 15.4 16.5 17.  15.7 14.9 14.9 12.3  9.1 10.5  9.9  8.2  4.5
  5.   7.3]

In [17]:
#a) Reshape into matrix form
#Assume each row is a day
#Reshape temperature into a (10, 24) matrix
temp_matrix = temp.reshape((10, 24))
print(temp_matrix, "\n")
#Calculate daily min, max, and mean using axis-based operations
dailymin=temp_matrix.min(axis=1)
print("dailymin:", dailymin)
dailymax=temp_matrix.max(axis=1)
print("dailymax:", dailymax)
dailymean=temp_matrix.mean(axis=1)
print("dailymean:", dailymean)

[[16.6 16.2 15.3 15.8 20.9 20.8 22.8 22.5 21.2 28.2 28.2 25.6 25.4 23.4
  27.6 23.8 22.  23.7 23.1 22.1 18.2 19.4 19.7 14.7]
 [15.9 15.7 17.6 20.  22.  21.2 22.7 21.5 23.6 28.7 20.5 25.1 22.1 24.5
  22.6 21.9 23.9 23.9 24.2 22.  19.9 18.8 16.5 18. ]
 [13.6 15.7 18.5 15.9 25.7 20.9 20.8 20.7 22.3 25.7 24.8 21.2 25.5 21.9
  22.4 24.7 24.4 24.4 23.3 24.4 22.7 20.9 18.6 15.4]
 [16.7 18.7 17.9 16.  21.5 22.1 27.1 23.7 21.9 24.2 26.8 24.4 24.4 25.7
  24.  19.5 23.  23.7 19.8 21.1 18.7 20.8 19.7 15.9]
 [19.7 12.4 18.7 18.9 21.2 21.  19.6 20.5 24.7 24.7 23.3 23.1 22.8 24.5
  24.9 24.7 24.1 22.5 24.2 23.3 22.2 23.9 16.8 18.4]
 [17.8 18.5 21.1 21.9 17.9 16.6 23.3 24.8 22.5 26.  25.4 24.3 26.2 20.8
  21.3 22.7 24.7 23.5 25.6 23.2 23.9 15.5 19.8 17.3]
 [15.8 17.6 17.9 17.9 19.8 23.4 19.9 25.7 23.1 25.9 24.4 22.5 24.8 24.5
  24.2 22.9 20.  20.7 20.5 21.9 23.2 15.4 15.3 17.6]
 [13.5 13.5 17.4 14.8 21.2 18.5 21.6 23.4 26.  22.3 22.3 24.9 23.7 23.7
  24.6 23.6 25.5 24.4 22.5 21.5 19.  17.3 15.2 17.9]
 [14.3 17.3 15.6 21.5 17.8 21.2 20.6 21.3 22.8 21.2 25.1 25.7 27.1 25.
  25.  23.7 21.5 24.3 23.6 18.6 19.6 14.7 19.  16.2]
 [17.7 16.3 16.8 17.3 20.  21.8 23.3 24.4 24.1 28.5 25.8 25.3 25.3 23.7
  24.  22.7 24.2 22.6 21.2 23.4 20.2 20.2 20.9 11.5]]

dailymin: [14.7 15.7 13.6 15.9 12.4 15.5 15.3 13.5 14.3 11.5]
dailymax: [28.2 28.7 25.7 27.1 24.9 26.2 25.9 26.  27.1 28.5]
dailymean: [21.55       21.36666667 21.43333333 21.55416667 21.67083333 21.85833333
 21.0375     20.7625     20.94583333 21.71666667]

In [18]:
# b) Normalize the temperature matrix
#Subtract the mean and divide by std deviation
#Do it manually using NumPy functions
def normalize(matrix):
    normalized_matrix=(matrix-matrix.mean())/matrix.std()
    return normalized_matrix
normalized_temp=normalize(temp_matrix)
print(normalized_temp)

[[-1.38980772 -1.50587692 -1.76703261 -1.62194611 -0.14206386 -0.17108116
   0.40926482  0.32221292 -0.05501196  1.97619897  1.97619897  1.2217492
   1.1637146   0.58336862  1.80209518  0.69943781  0.17712643  0.67042051
   0.49631672  0.20614373 -0.92553093 -0.57732335 -0.49027145 -1.9411364 ]
 [-1.59292881 -1.65096341 -1.09963473 -0.40321955  0.17712643 -0.05501196
   0.38024752  0.03203993  0.64140321  2.12128547 -0.25813306  1.0766627
   0.20614373  0.90255891  0.35123022  0.14810913  0.72845511  0.72845511
   0.81550701  0.17712643 -0.43223685 -0.75142714 -1.41882502 -0.98356553]
 [-2.26032669 -1.65096341 -0.83847904 -1.59292881  1.25076649 -0.14206386
  -0.17108116 -0.20009846  0.26417833  1.25076649  0.9896108  -0.05501196
   1.1927319   0.14810913  0.29319563  0.9605935   0.87354161  0.87354161
   0.55435132  0.87354161  0.38024752 -0.14206386 -0.80946174 -1.73801531]
 [-1.36079042 -0.78044444 -1.01258283 -1.56391151  0.03203993  0.20614373
   1.65700868  0.67042051  0.14810913  0.81550701  1.56995678  0.87354161
   0.87354161  1.25076649  0.75747241 -0.54830605  0.46729942  0.67042051
  -0.46125415 -0.08402926 -0.78044444 -0.17108116 -0.49027145 -1.59292881]
 [-0.49027145 -2.60853428 -0.78044444 -0.72240984 -0.05501196 -0.11304656
  -0.51928875 -0.25813306  0.9605935   0.9605935   0.55435132  0.49631672
   0.40926482  0.90255891  1.0186281   0.9605935   0.78648971  0.32221292
   0.81550701  0.55435132  0.23516103  0.72845511 -1.33177312 -0.86749634]
 [-1.04160013 -0.83847904 -0.08402926  0.14810913 -1.01258283 -1.38980772
   0.55435132  0.9896108   0.32221292  1.33781839  1.1637146   0.84452431
   1.39585299 -0.17108116 -0.02599466  0.38024752  0.9605935   0.61238592
   1.2217492   0.52533402  0.72845511 -1.70899801 -0.46125415 -1.18668663]
 [-1.62194611 -1.09963473 -1.01258283 -1.01258283 -0.46125415  0.58336862
  -0.43223685  1.25076649  0.49631672  1.30880109  0.87354161  0.32221292
   0.9896108   0.90255891  0.81550701  0.43828212 -0.40321955 -0.20009846
  -0.25813306  0.14810913  0.52533402 -1.73801531 -1.76703261 -1.09963473]
 [-2.28934399 -2.28934399 -1.15766933 -1.9121191  -0.05501196 -0.83847904
   0.06105723  0.58336862  1.33781839  0.26417833  0.26417833  1.0186281
   0.67042051  0.67042051  0.9315762   0.64140321  1.1927319   0.87354161
   0.32221292  0.03203993 -0.69339254 -1.18668663 -1.79604991 -1.01258283]
 [-2.0572056  -1.18668663 -1.67998071  0.03203993 -1.04160013 -0.05501196
  -0.22911576 -0.02599466  0.40926482 -0.05501196  1.0766627   1.25076649
   1.65700868  1.0476454   1.0476454   0.67042051  0.03203993  0.84452431
   0.64140321 -0.80946174 -0.51928875 -1.9411364  -0.69339254 -1.50587692]
 [-1.07061743 -1.47685962 -1.33177312 -1.18668663 -0.40321955  0.11909183
   0.55435132  0.87354161  0.78648971  2.06325087  1.27978379  1.1346973
   1.1346973   0.67042051  0.75747241  0.38024752  0.81550701  0.35123022
  -0.05501196  0.58336862 -0.34518495 -0.34518495 -0.14206386 -2.86968997]]

In [19]:
#c) Apply custom mask/filter
# TODO: Create boolean mask and filter wind speeds
mask = wind > 15
high_wind = wind[mask]

print("mask:", mask)
print("\nhigh wind readings:", high_wind)
print("\nnumber of high wind readings:", high_wind.size)

mask: [False False False False False False False False False False False  True
  True  True False False False False False False False False False False
 False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False False False False False False  True  True  True
  True False False  True  True False False False False False False False
 False False False False False False False False False False False  True
  True False False False False False False False False False False False
 False False False False False False False False False  True False  True
  True False  True False False False False False False False False False
 False False False False False False False False False False False False
 False  True False False False False False False False False False False
 False False False False False False False False False False  True  True
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
  True  True False False False False False False False False False False
 False False False False False False False False False  True  True False
 False  True False False  True False False False False False False False
 False False False False False False False False False False  True  True
  True  True False False False False False False False False False False]

high wind readings: [17.6 16.  16.5 16.3 16.7 15.8 17.8 15.1 16.3 15.2 17.  15.9 15.6 15.8
 15.4 15.6 16.3 15.3 16.2 16.9 15.3 15.2 15.5 17.4 17.4 15.4 15.4 16.5
 17.  15.7]

number of high wind readings: 30

## Final Challenge: Write Your Own Function

In [21]:
#Write a function `daily_summary(matrix)`
humidity_matrix = df['humidity_%'].to_numpy().reshape((10, 24))
pressure_matrix = df['pressure_hPa'].to_numpy().reshape((10, 24))
visibility_matrix = df['visibility_km'].to_numpy().reshape((10, 24))
wind_matrix = wind.reshape((10, 24))

In [22]:
def daily_summary(temp_matrix, humidity_matrix, wind_matrix, pressure_matrix, visibility_matrix):
    summaries = []
    num_days = temp_matrix.shape[0]  # 10

    for i in range(num_days):
        summary = {
            "temperature": {
                "min": temp_matrix[i].min(),
                "max": temp_matrix[i].max(),
                "mean": temp_matrix[i].mean()
            },
            "humidity": {
                "min": humidity_matrix[i].min(),
                "max": humidity_matrix[i].max(),
                "mean": humidity_matrix[i].mean()
            },
            "wind_speed": {
                "min": wind_matrix[i].min(),
                "max": wind_matrix[i].max(),
                "mean": wind_matrix[i].mean()
            },
            "pressure": {
                "min": pressure_matrix[i].min(),
                "max": pressure_matrix[i].max(),
                "mean": pressure_matrix[i].mean()
            },
            "visibility": {
                "min": visibility_matrix[i].min(),
                "max": visibility_matrix[i].max(),
                "mean": visibility_matrix[i].mean()
            }
        }
        summaries.append(summary)

    return summaries

summaries = daily_summary(temp_matrix, humidity_matrix, wind_matrix, pressure_matrix, visibility_matrix)
for i, s in enumerate(summaries):
    print(f"Day {i+1}: {s}\n")

Day 1: {'temperature': {'min': 14.7, 'max': 28.2, 'mean': 21.55}, 'humidity': {'min': 50.7, 'max': 78.5, 'mean': 65.37083333333334}, 'wind_speed': {'min': 1.3, 'max': 17.6, 'mean': 9.808333333333335}, 'pressure': {'min': 1002.3, 'max': 1022.9, 'mean': 1012.4416666666666}, 'visibility': {'min': 8.9, 'max': 11.5, 'mean': 10.291666666666666}}

Day 2: {'temperature': {'min': 15.7, 'max': 28.7, 'mean': 21.366666666666664}, 'humidity': {'min': 51.8, 'max': 83.2, 'mean': 67.35000000000001}, 'wind_speed': {'min': 3.2, 'max': 16.3, 'mean': 9.875}, 'pressure': {'min': 999.8, 'max': 1024.1, 'mean': 1011.7791666666666}, 'visibility': {'min': 8.0, 'max': 11.8, 'mean': 10.016666666666667}}

Day 3: {'temperature': {'min': 13.6, 'max': 25.7, 'mean': 21.433333333333334}, 'humidity': {'min': 50.0, 'max': 78.8, 'mean': 66.20833333333333}, 'wind_speed': {'min': 4.7, 'max': 17.8, 'mean': 10.916666666666666}, 'pressure': {'min': 1007.2, 'max': 1027.0, 'mean': 1013.0208333333334}, 'visibility': {'min': 8.8, 'max': 11.5, 'mean': 10.25}}

Day 4: {'temperature': {'min': 15.9, 'max': 27.1, 'mean': 21.554166666666664}, 'humidity': {'min': 54.0, 'max': 88.1, 'mean': 67.08749999999999}, 'wind_speed': {'min': 3.2, 'max': 17.0, 'mean': 10.058333333333332}, 'pressure': {'min': 1003.4, 'max': 1023.8, 'mean': 1013.8291666666668}, 'visibility': {'min': 6.8, 'max': 11.8, 'mean': 9.791666666666666}}

Day 5: {'temperature': {'min': 12.4, 'max': 24.9, 'mean': 21.670833333333334}, 'humidity': {'min': 52.4, 'max': 82.3, 'mean': 66.87916666666666}, 'wind_speed': {'min': 4.8, 'max': 15.8, 'mean': 10.0375}, 'pressure': {'min': 1004.2, 'max': 1019.7, 'mean': 1012.1041666666666}, 'visibility': {'min': 8.3, 'max': 12.6, 'mean': 10.075000000000001}}

Day 6: {'temperature': {'min': 15.5, 'max': 26.2, 'mean': 21.858333333333334}, 'humidity': {'min': 53.1, 'max': 82.1, 'mean': 67.28333333333333}, 'wind_speed': {'min': 3.7, 'max': 16.3, 'mean': 9.816666666666668}, 'pressure': {'min': 1003.6, 'max': 1019.0, 'mean': 1011.1708333333332}, 'visibility': {'min': 8.1, 'max': 12.4, 'mean': 9.775}}

Day 7: {'temperature': {'min': 15.3, 'max': 25.9, 'mean': 21.037499999999998}, 'humidity': {'min': 53.9, 'max': 80.8, 'mean': 65.75833333333333}, 'wind_speed': {'min': 3.7, 'max': 16.2, 'mean': 10.0125}, 'pressure': {'min': 998.1, 'max': 1017.9, 'mean': 1010.5499999999998}, 'visibility': {'min': 9.0, 'max': 11.3, 'mean': 10.070833333333333}}

Day 8: {'temperature': {'min': 13.5, 'max': 26.0, 'mean': 20.7625}, 'humidity': {'min': 49.9, 'max': 83.3, 'mean': 68.1125}, 'wind_speed': {'min': 3.8, 'max': 16.9, 'mean': 10.058333333333334}, 'pressure': {'min': 1002.7, 'max': 1019.2, 'mean': 1010.4833333333332}, 'visibility': {'min': 7.9, 'max': 11.6, 'mean': 9.625}}

Day 9: {'temperature': {'min': 14.3, 'max': 27.1, 'mean': 20.945833333333336}, 'humidity': {'min': 51.8, 'max': 86.6, 'mean': 67.1375}, 'wind_speed': {'min': 4.4, 'max': 17.4, 'mean': 10.033333333333333}, 'pressure': {'min': 1000.2, 'max': 1022.8, 'mean': 1012.0208333333334}, 'visibility': {'min': 8.1, 'max': 11.9, 'mean': 10.0375}}

Day 10: {'temperature': {'min': 11.5, 'max': 28.5, 'mean': 21.71666666666667}, 'humidity': {'min': 47.8, 'max': 80.1, 'mean': 66.80000000000001}, 'wind_speed': {'min': 4.5, 'max': 17.0, 'mean': 10.454166666666666}, 'pressure': {'min': 1000.1, 'max': 1024.2, 'mean': 1011.7583333333333}, 'visibility': {'min': 7.8, 'max': 12.5, 'mean': 10.095833333333333}}